name: ${pom.name}
main: tk.kirlian.duckshop.DuckShop
version: ${pom.version}
author: Chris Wong
description: Create fully automated shops with signs!
commands:
    duckshop:
        description: Do various things with signs.
        usage: |
               /<command> link - link a sign with a chest.
